FROM openjdk:8u191-jre-alpine
MAINTAINER Allan Guan <allanzguan@gmail.com>
EXPOSE 8080
COPY spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar /.
ENTRYPOINT ["java", "-jar", "spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar"]
